apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sm-config
  labels:
    {{- include "stream-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: stream-manager
data:
  config.toml: |
    bind_ip = "0.0.0.0"
    port = {{ .Values.streamManager.port }}
    mysql_host = "{{ .Release.Name }}-mysql"
    mysql_port = {{ .Values.mysql.port }}
    mysql_username = "root"
    mysql_password = {{ .Values.mysql.rootPassword | quote }}
    mysql_database = {{ .Values.mysql.database | quote }}
    default_replication_factor = {{ .Values.streamManager.replicationFactor }}
    heartbeat_check_interval_ms = {{ .Values.streamManager.heartbeatCheckIntervalMs }}
