apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-init
  labels:
    {{- include "stream-store.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};
