name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.4"
        root-password: password
    - run: mysql -uroot -e 'SELECT version()'
    - run: mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS stream_store'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
