name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: ap-guangzhou
  AWS_ENDPOINT_URL: https://cos.ap-guangzhou.myqcloud.com
  AWS_S3_ADDRESSING_STYLE: virtual
  CARGO_TERM_COLOR: always    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.4"
        root-password: password
    - run: mysql -uroot -ppassword -e 'SELECT version()'
    - run: mysql -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS stream_store'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Benchmarks
      env:
        RUST_LOG: "warn"
      run: cargo bench --bench pipeline_append

  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.4"
        root-password: password
    - run: mysql -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS stream_store'
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: lcov.info
        fail_ci_if_error: false
